DELETE FROM AUTHORS WHERE ID IN (1,2,3,4,5);

INSERT INTO AUTHORS (ID, AUTHOR_NAME, AUTHOR_NAT) Values (1, 'Sunny', 'HK');
INSERT INTO AUTHORS (ID, AUTHOR_NAME, AUTHOR_NAT) Values (2, 'Owie', 'HK');

COMMIT;

