server:
  port: 8085

spring.datasource:
  url: jdbc:mysql://localhost:3306/sys
  username: sunnyng
  password: Prun1234.
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true

spring.sql:
  init:
    mode: always
    schema-locations: classpath:DDL_STUDENTS.sql
    data-locations: classpath:DML_STUDENTS.sql

