server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: sunnyng
    password: Prun1234.
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:DDL_SUPPLIER.sql,classpath:DDL_GOODS.sql
      data-locations: classpath:DML_SUPPLIER.sql, classpath:DML_GOODS.sql
      mode: always
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true