

CREATE TABLE GOODS(
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  GOODS_NAME VARCHAR(130) NOT NULL,
  GOODS_SUPPLIER_ID INTEGER NOT NULL,
  PUBLIC_DATE DATE NOT NULL,
  CONSTRAINT FK_GOODS FOREIGN KEY(GOODS_SUPPLIER_ID) REFERENCES SUPPLIER(ID)
);