INSERT INTO GOODS(ID, GOODS_NAME, GOODS_SUPPLIER_ID, PUBLIC_DATE) VALUES (1, 'GOOD A', 1, '2011-04-05');
INSERT INTO GOODS(ID, GOODS_NAME, GOODS_SUPPLIER_ID, PUBLIC_DATE) VALUES (2, 'GOOD B', 2, '2011-07-05');
INSERT INTO GOODS(ID, GOODS_NAME, GOODS_SUPPLIER_ID, PUBLIC_DATE) VALUES (3, 'GOOD C', 2, '2019-11-05');
COMMIT;